apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app-deploy
spec:
  selector:
    matchLabels:
      app: app-deploy
  template:
    metadata:
      labels:
        app: app-deploy
      {{- if .Values.metrics }}  
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '80'
      {{- end }}            
    spec:
      containers:
      - name: app
        image: fabricioveronez/metricasapi
        ports:
        - containerPort: 80
        env:
          - name: "MONGODB_URI"
            value: "mongodb://{{ .Values.mongoDb.rootUser }}:{{ .Values.mongoDb.rootPassword }}@{{ .Release.Name }}-mongodb-service:27017/admin"
            