apiVersion: v1
kind: Service
metadata:
  name: teste-app-service
spec:
  selector:
    app: app-deploy
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: teste-mongodb-service
spec:
  selector:
    app: mongodb-deploy
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb
  - port: 9216
    targetPort: 9216
    name: exporter
  type: LoadBalancer